Fix CLI for latest Werkzeug (2.0.0rc1)
pallets/flask pull request #3910
Opened 2021-02-16 08:00 UTC by ziddey

Wrap the `isinstance` check in a try/except to ignore failing objects (LocalProxy outside app context).

"LocalProxy matches the current Python data model special methods, including all r-ops, in-place ops, and async. class is proxied, so the proxy will look like the object in more cases, including isinstance. Use issubclass(type(obj), LocalProxy) to check if an object is actually a proxy. :issue:1754"

- fixes #3909 

Checklist:

- [X] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [X] Run `pre-commit` hooks and fix any issues.
- [X] Run `pytest` and `tox`, no tests failed.

2021-02-18 16:46 UTC, davidism commented
I think we came up with a better solution to this by telling `LocalProxy` about its type even when unbound. I'll leave this open until I make sure that works.

2021-02-19 19:07 UTC, recepsirin commented on src/flask/cli.py
> +            pass
Please, handle the possible exceptions because unless you handle them both explicitly or implicitly are meaningless.

2021-02-19 19:08 UTC, recepsirin requested changes
Please, handle the possible exceptions because unless you handle them both explicitly or implicitly are meaningless.

2021-03-08 16:30 UTC, davidism commented
Fixed in https://github.com/pallets/werkzeug/pull/2042, specifically 352cd7167984f805daf226966f38f8dfeb991313.

2021-03-08 16:30 UTC, closed without merging